// binary representation
// attribute size in bytes (16), flags(16), handle (16), uuid (16/128), value(...)

#ifndef _LE_SERVER_MODULE_H_
#define _LE_SERVER_MODULE_H_

#include <stdint.h>
#include <le_user.h>
#include "uart_user.h"

#define CMD_AUTO_FEEDBACK_EN 	0

//
// gatt profile include file, generated by jieli gatt_inc_generator.exe
//

const uint8_t profile_data[] = 
{
    //////////////////////////////////////////////////////
    //
    // 0x0001 PRIMARY_SERVICE  ae00
    //
    //////////////////////////////////////////////////////
    0x0a, 0x00, 0x02, 0x00, 0x01, 0x00, 0x00, 0x28, 0x00, 0xae,

     /* CHARACTERISTIC,  ae01, WRITE | DYNAMIC, */
    // 0x0002 CHARACTERISTIC ae01 WRITE | DYNAMIC 
    0x0d, 0x00, 0x02, 0x00, 0x02, 0x00, 0x03, 0x28, 0x08, 0x03, 0x00, 0x01, 0xae,
    // 0x0003 VALUE ae01 WRITE | DYNAMIC  
    0x08, 0x00, 0x08, 0x01, 0x03, 0x00, 0x01, 0xae,

     /* CHARACTERISTIC,  ae02, NOTIFY, */
    // 0x0004 CHARACTERISTIC ae02 NOTIFY 
    0x0d, 0x00, 0x02, 0x00, 0x04, 0x00, 0x03, 0x28, 0x10, 0x05, 0x00, 0x02, 0xae,
    // 0x0005 VALUE ae02 NOTIFY  
    0x08, 0x00, 0x10, 0x00, 0x05, 0x00, 0x02, 0xae,
    // 0x0006 CLIENT_CHARACTERISTIC_CONFIGURATION 
    0x0a, 0x00, 0x0a, 0x01, 0x06, 0x00, 0x02, 0x29, 0x00, 0x00,

    // END
    0x00, 0x00, 
}; 
//
// characteristics <--> handles
//
#define ATT_CHARACTERISTIC_ae01_01_VALUE_HANDLE 0x0003
#define ATT_CHARACTERISTIC_ae02_01_VALUE_HANDLE 0x0005
#define ATT_CHARACTERISTIC_ae02_01_CLIENT_CONFIGURATION_HANDLE 0x0006

#endif
